import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css"; // <-- این خط بسیار حیاتی است

export const metadata: Metadata = {
  title: "Footzi - آنالیز فوتبال",
  description: "اپلیکیشن آنالیز آمار فوتبال لیگ برتر انگلیس",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> b7e3c7310cdd301a4f6dfe8c525db33518574998
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> b7e3c7310cdd301a4f6dfe8c525db33518574998
